title: Einfache Seite

icon: 📝

options:
  preview: "{{ page.frontendUrl }}"

columns:
  - width: 2/3
    sections:
      text: sections/text

  - width: 1/3
    sections:
      cover: sections/cover
      description: sections/description
      images: sections/images
      helpers: sections/punctuation
