title: Einfache Seite

icon: 📝

options:
  preview: "{{ page.frontendUrl }}"

columns:
  - width: 2/3
    sections:
      text: sections/text

  - width: 1/3
    sections:
      meta:
        type: fields
        fields:
          cover: fields/cover
          description: fields/description
      images: sections/images
