title: Einfache Seite

icon: 📝

options:
  preview: "{{ page.frontendUrl }}"

tabs:
  content:
    label: Inhalt
    icon: draft
    sections:
      text: sections/text

  seo:
    label: SEO
    icon: search
    sections:
      meta: sections/meta

  images: tabs/images
