title: Einfache Seite

icon: 📝

columns:
  - width: 2/3
    sections:
      text: sections/text

  - width: 1/3
    sections:
      cover: sections/cover
      description: fields/description
      images: sections/images
      helpers: sections/punctuation
