title: Übersicht

columns:
  - width: 1/2
    sections:
      albums: sections/badgers

  - width: 1/2
    sections:
      notes: sections/notes

      pages:
        type: pages
        create: default
        templates:
          - about
          - home
          - default
