title: Übersicht

options:
  preview: "{{ site.frontendUrl }}"

tabs:
  dashboard:
    label: Inhalt
    icon: draft
    columns:
      - width: 1/2
        sections:
          badgers: sections/badgers

      - width: 1/2
        sections:
          notes: sections/notes

          pages:
            type: pages
            label: Seiten
            create: default
            templates:
              - about
              - backers
              - default
              - error
              - home
              - notes

  settings:
    label: Einstellungen
    icon: settings
    columns:
      - width: 1/2
        sections:
          content:
            type: fields
            fields:
              footer:
                label: Fußzeile
                type: pages

      - width: 1/2
        sections:
          meta:
            type: fields
            fields:
              cover:
                extends: fields/cover
                query: site.files.template("image")
              description: fields/description
