title: Übersicht

tabs:
  dashboard:
    label: Inhalt
    icon: draft
    columns:
      - width: 1/2
        sections:
          albums: sections/badgers

      - width: 1/2
        sections:
          notes: sections/notes

          pages:
            type: pages
            headline: Seiten
            create: default
            templates:
              - about
              - default
              - home
              - notes

  settings:
    label: Einstellungen
    icon: settings
    columns:
      - width: 1/2
        sections:
          content:
            type: fields
            fields:
              footer:
                label: Fußzeile
                type: pages

      - width: 1/2
        sections:
          meta:
            type: fields
            fields:
              description: fields/description
